@baseUrl = http://localhost:4000

### Pegar usuários
GET {{baseUrl}}/teste

### Cadastro
POST {{baseUrl}}/cadastro
Content-Type: application/json

{
    "nome":"g",
    "email":"gustavo13725@mail.com",
    "senha":"123456"
}

### Login

POST {{baseUrl}}/login
Content-Type: application/json

{
    "nome":"gustavo",
    "email":"g@mail.com",
    "senha":"123456"
}